### ISSUE TITLE
Error when invoking update_state

### ISSUE THREAD

**Issue by anweiss** [hyperledgendary/fabric-contract-api-rust#26]
When attempting to call `Collection::update_state(key, data)` against the `World` state, I get the following error:

```
Error: endorsement failure during query. response: status:500 message:"error invoking guest: Failed to call the `__guest_call` exported function."
```

Not sure if the implementation for this function is incomplete or if this is a legitimate bug. Looks to be generated from the `wapc-guest` crate.

**Comment by anweiss** [comment]
Some more detail:

```
ERROR - [Panic]panicked at 'called `Result::unwrap()` on an `Err` value: Error(HostError("Operation not supported: LedgerService UpdateState"))',/fabric-contract-api-rust/fabric_contract/src/runtimeapi/wapc.rs:58:5[/Panic]
```

Originating from https://github.com/hyperledgendary/fabric-contract-api-rust/blob/master/fabric_contract/src/runtimeapi/wapc.rs#L58

**Comment by mbwhite** [comment]
@anweiss   yes.. it's not yet implemented sadly.

**Comment by jt-nti** [comment]
WASM is not currently being considered for upcoming Fabric versions and since there hasn't been any activity in this repository for a while, I'm planning to archive it.
