### ISSUE TITLE
Refactor runtime/wapc.rs to separate crate

### ISSUE THREAD

**Issue by mbwhite** [hyperledgendary/fabric-contract-api-rust#40]
When a innvocation comes in from the peer, waPC is called with the 'invokeTransaction' command; the payload is a protobuf that is decoded. It's then passed directly onto the ContractAPI for final routing and processing.

To make it easier to interact with different implementations it's worth looking into how to separate out this into it's own crate.

**Comment by mbwhite** [comment]
fyi @seanyoung based on our discussion

**Comment by jt-nti** [comment]
WASM is not currently being considered for upcoming Fabric versions and since there hasn't been any activity in this repository for a while, I'm planning to archive it.
