### ISSUE TITLE
Timeline to move from Preview -> Production Ready?  

### ISSUE THREAD

**Issue by likeabbas** [hyperledgendary/fabric-contract-api-rust#51]
@mbwhite Is this project still being maintained? Is there an issue in starting new projects with this?

**Comment by jt-nti** [comment]
Hi @likeabbas, this project was part of an investigation in to making use of Wasm in Hyperledger Fabric. There's still an RFC around with some more info -> hyperledger/fabric-rfcs#28
Unfortunately this project is not currently being actively worked on (maybe we should archive the Wasm projects @mbwhite?) but it would be really interesting to know what new projects you had in mind and whether it was Wasm, or Rust, or something else which you were keen to take advantage of.

**Comment by likeabbas** [comment]
Hi @jt-nti, 

thanks for getting back! I was looking in to this project because I have a potential start up idea that perfectly suits hyperledger fabric. I’ve used Go and Typescript to write chain code. I far preferred Typescript due to the robustness of the language and type features, but I worry about the performance of typescript at scale. Rust seemed like the perfect compromise (also since it’s the language I’m most familiar with). I would be happy to chat about this sometime!

**Comment by jt-nti** [comment]
@likeabbas ah, that makes sense. This probably isn't the project you're looking for in that case- we used Rust because it worked well with Wasm, but this isn't a Rust chaincode implementation in the same way as the Java, Go and Node supported chaincode implementations. A fully Rust chaincode implementation, i.e. without the https://github.com/hyperledgendary/fabric-chaincode-wasm bit, would be an interesting addition but I don't think it's very likely to happen sadly.

**Comment by likeabbas** [comment]
@jt-nti  I read this in the RFC 

> We actually want to deprecate the current chaincode model over time. While the current chaincode implementation made sense at the time given we did not want to write our own virtual machine / byte code interpreter as well as the fact that we did not feel EVM byte code would meet all of our needs, if something like WebAssembly had existed at the time, it's the route we would have taken.

Is WASM (and, by extension, this crate) no longer being considered for the future of Fabric implementations?

**Comment by jt-nti** [comment]
WASM is not currently being considered for upcoming Fabric versions and since there hasn't been any activity in this repository for a while, I'm planning to archive it.
