### ISSUE TITLE
version miss match

### ISSUE THREAD

**Issue by greenpdx** [hyperledgendary/fabric-contract-api-rust#52]
I am following the instructions on
https://hyperledgendary.github.io/fabric-contract-api-rust/guides/getting-started.html

I get to the part
docker exec humboldt.cli mknet.sh

2023-01-04 12:51:27.253 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: got unexpected status: BAD_REQUEST -- error applying config update to existing channel 'smallchannel': error authorizing update: error validating ReadSet: proposed update requires that key [Group]  /Channel/Application be at version 0, but it is currently at version 1

**Comment by jt-nti** [comment]
WASM is not currently being considered for upcoming Fabric versions and since there hasn't been any activity in this repository for a while, I'm planning to archive it.
