### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by echos2019** [hyperledgendary/fabric-contract-api-rust#54]
fabric-contract-api-rust cannot be build by cargo build --target wasm32-unknown-unknown, there are 160 problem
I build the project by https://hyperledgendary.github.io/fabric-contract-api-rust/guides/getting-started.html
is the project still be maintenanced ?
![image](https://user-images.githubusercontent.com/60174469/218467390-46ae8500-0724-45d2-8d19-546e6575beb8.png)

**Comment by jt-nti** [comment]
Sorry, this repository hasn't been maintained for a while. WASM is not currently being considered for upcoming Fabric versions so I'm planning to archive it to avoid confusion.
